<?php 
    /* Disclaimer:
     * - The components "header" and "sidebar" are a core part of this page, and are intrinsically related to this file and to PHP itself
     * - Other components, mainly and almost only the table part is mean to be fully generated by JavaScript, that receives the data by
     * connection with the PHP back-end via endpoints
     */

    include_once "components/header.php";
    include_once "components/sidebar.php";

    require_once __DIR__ . "/../../autoload.php";

    $payload = utilities\JWT::verifyJWT($_COOKIE["admin_token"]);

    $username = $payload["username"];
    $access = [
        "name" => "Admin",
        "permissions" => [
            "Inserir",
            "Alterar",
            "Excluir"
        ]
    ];
?>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> QuickMart | Painel de Administrador </title>
    <link rel="icon" type="image/x-icon" href="/quickmart/assets/images/icon_transparente.png">
    <link rel="stylesheet" href="/quickmart/assets/css/main.css">
    <link rel="stylesheet" href="/quickmart/assets/css/admin.css">
</head>
<body style="display: none;" class="bg-neutral-100">
    <div class="flex flex-col w-screen h-screen overflow-hidden">
        <?php generateHeader($username, $access) ?>

        <main class="relative flex-1 flex overflow-hidden">
            <!-- Side Bar -->
            <?php generateSidebar($access) ?>

            <!-- Table and stuff -->
            <div id="side-container" class="absolute top-0 right-0 w-[calc(100%-16rem)] h-full p-4 transition-all duration-700"></div>
        </main>
    </div>

    <script type="module" src="/quickmart/assets/js/admin/main.js"></script>
</body>
</html>
