<?php 
    /* Disclaimer:
     * - The variables $username and $access are not mean to be defined here, they should be defined at the AdminController
     * - The components "header" and "sidebar" are a core part of this page, and are intrinsically related to this file and to PHP itself
     * - Other components, mainly and almost only the table part is mean to be fully generated by JavaScript, that receives the data by
     * connection with the PHP back-end via endpoints
     */

    include_once "components/header.php";
    include_once "components/sidebar.php";

    $username = "Neo";
    $access = [
        "name" => "Admin",
        "permissions" => [
            "Inserir",
            "Alterar",
            "Excluir"
        ]
    ];
?>

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> QuickMart | Painel de Administrador </title>
    <link rel="stylesheet" href="/quickmart/assets/css/main.css">
    <link rel="stylesheet" href="/quickmart/assets/css/admin.css">
</head>
<body class="hidden bg-neutral-100">
    <div class="flex flex-col w-screen h-screen overflow-hidden">
        <?php generateHeader($username, $access) ?>

        <main class="relative flex-1">
            <!-- Side Bar -->
            <?php generateSidebar($access) ?>

            <!-- Table and stuff -->
            <div id="side-container" class="hidden absolute top-0 right-0 w-[calc(100%-16rem)] h-full p-8 transition-all duration-700">
                <div class="flex flex-col gap-4 w-full h-full *:w-full *:bg-white *:rounded-md *:shadow-sm">
                    <!-- Header -->
                    <header class="flex justify-between items-center px-4 py-2">
                        <div class="text-lg">
                            <span class="opacity-80 mr-2">Tabela: </span>
                            <span>Produto</span>
                        </div>
                        <button type="button" class="text-white font-bold px-8 py-2 rounded-md bg-primary hover:bg-primary-dark">
                            Novo Registro
                        </button>
                    </header>
                    
                    <!-- Search bar and Table -->
                    <div class="flex-1 flex flex-col p-4 *:w-full">
                        <!-- Search bar -->
                        <div>
                            <form action="" class="flex gap-4 w-full">
                                <label 
                                    for="search-input" 
                                    class="hidden"></label>
                                <input 
                                    required
                                    type="search" 
                                    name="search-input" 
                                    id="search-input" 
                                    placeholder="Pesquise pelo nome" 
                                    class="
                                        flex-1 px-4 py-1 bg-neutral-100 
                                        border-2 border-transparent 
                                        rounded-md outline-none focus:border-secondary
                                    ">
                                <button 
                                    type="submit" 
                                    class="
                                        text-white font-bold 
                                        px-4 py-1 
                                        rounded-md 
                                        bg-primary hover:bg-primary-dark
                                    ">
                                    Pesquisar
                                </button>
                            </form>
                        </div>

                        <hr class="border-t-2 my-4">
                        
                        <!-- Table -->
                        <div class="flex-1 bg-red-500">
                            <!--  TODO: all the rest -->
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>

    <!-- To import JavaScript files that require other JavaScript files, specify the type (module) and the type (text/javascript) -->
    <!-- Im not sure why I need to type the same thing twice, but it works anyway -->
    <script type="module" type="text/javascript" src="/quickmart/assets/js/admin.js"></script>
</body>
</html>
